### ISSUE TITLE
Using Custom Themes

### ISSUE THREAD

**Issue by danvega** [EldoranDev/gridsome-plugin-remark-shiki#10]
Any idea of how to use a custom theme with this plugin? The Shiki docs say that you can use any vscode theme 

```
const shiki = require('shiki')

const t = shiki.loadTheme('./solarized-dark.tmTheme')

shiki.getHighlighter({
  theme: t
})
```

I use [Synthwave 84 ](https://github.com/robb0wen/synthwave-vscode) but I'm not quite sure I can just drop it in my project and use it and therefore I am having a tough time. Any ideas?

**Comment by Microflash** [comment]
@danvega You can simply copy and paste [synthwave-color-theme.json](https://raw.githubusercontent.com/robb0wen/synthwave-vscode/master/themes/synthwave-color-theme.json) in say, `static` directory, and then use the following config in your `gridsome.config.js`:

```js
const shiki = require('shiki');

const synthwave= shiki.loadTheme('./static/synthwave-color-theme.json');

module.exports = {
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'blog/**/*.md',
        typeName: 'Post',
        remark: {
          plugins: [
            ['gridsome-plugin-remark-shiki', { theme: synthwave, skipInline: true }]
          ]
        }
      }
    }
  ]
}
```
