### ISSUE TITLE
Doesn't work with gridsome-vue-remark

### ISSUE THREAD

**Issue by D-Marc1** [EldoranDev/gridsome-plugin-remark-shiki#16]
I have the following configuration, but it's not adding syntax highlighting to my code. Am I doing something wrong?

```js
module.exports = {
  plugins: [
    {
      use: '@gridsome/vue-remark',
      options: {
        typeName: 'BlogPost', // Required
        baseDir: './blog/posts', // Where .md files are located
        template: './src/templates/BlogPost.vue', // Optional
        remark: {
          plugins: [
            [
              'gridsome-plugin-remark-shiki',
              { theme: 'nord', skipInline: false },
            ],
          ],
        },
      },
    },
  ],
};
```

**Comment by EldoranDev** [comment]
Nothing wrong on the first look, I'll check deeper later today.

**Comment by EldoranDev** [comment]
okay, apparently the configuration for vue-remark and the transformer-remark are differnt.

The plugin config needs to get moved into the plugin config as the there listed plugins are used by the vue-remark.

```js
module.exports = {
  plugins: [
    {
      use: '@gridsome/vue-remark',
      options: {
        typeName: 'BlogPost', // Required
        baseDir: './blog/posts', // Where .md files are located
        template: './src/templates/BlogPost.vue', // Optional
       plugins: [
          [
            'gridsome-plugin-remark-shiki',
            { theme: 'nord', skipInline: false },
          ],
        ],
     },
    },
  ],
};
```

**Comment by D-Marc1** [comment]
Thank you for the quick reply! I did make an error in the syntax as you pointed out also. I updated the original comment to place `remark` inside `options`. 

I'm not sure why Gridsome made these plugins so much different when they actually made them both and accomplish the same task, only `vue-remark` can do much more

**Comment by D-Marc1** [comment]
@EldoranDev wait, I'm confused. Why was this issue closed?

**Comment by D-Marc1** [comment]
Oh wait, nvm. I'm an idiot. I didn't realize the `remark` outer layer was removed in your comment. Thanks again!
