### ISSUE TITLE
min theme not supported

### ISSUE THREAD

**Issue by Berkmann18** [EldoranDev/gridsome-plugin-remark-shiki#6]
While trying out some themes on https://github.com/Berkmann18/gridsome-starter-netlify-netlifycms-tailwindcss, I encountered this error:
```
An error occurred while executing page-query for src/templates/Post.vue

Error: No theme min found

GraphQL request (6:5)
5:     date(format: "MMM D YYYY")
6:     timeToRead
       ^
7:     tags
```
I tried with the default theme (`nord`, even when I explicitly specified it) which worked but the [min theme](https://github.com/misolori/min-theme) doesn't.

**Comment by EldoranDev** [comment]
Try to use "min-light" or "min-dark".

**Comment by Berkmann18** [comment]
Both work although they produce a dark looking code block with what seems to be highlighting issues.

With `mini-dark`:
![mini-dark](https://user-images.githubusercontent.com/8260834/56037536-6ddfc500-5d27-11e9-93dc-cb4821759e9f.PNG)
With `mini-light`:
![mini-light](https://user-images.githubusercontent.com/8260834/56037537-6e785b80-5d27-11e9-89a0-eb01d16d5aa4.PNG)

**Comment by EldoranDev** [comment]
I'll look into that.

could you send me the code block you use or point me to the repository ?

**Comment by Berkmann18** [comment]
Sure, here's the [repo](https://github.com/Berkmann18/gridsome-starter-netlify-netlifycms-tailwindcss/tree/codeblock) as off before trying the `min-light`/`min-dark`.

The code block in the images above can be found [here](https://github.com/Berkmann18/gridsome-starter-netlify-netlifycms-tailwindcss/blob/codeblock/posts/2019-03-24-this-is-an-example.md).

**Comment by EldoranDev** [comment]
okay, to fix the syntax highlighting you'll have to switch to vue / vue-htm instead of javascript as language.

Why the background is wrong I'll have to investigate, I'll look into it as fast as I can.

**Comment by Berkmann18** [comment]
Okay, I've tried `vue` and `vue-html` and `vue-html` seems to highlight things properly (compared to `vue` which does it except for `<page-query>`).

**Comment by EldoranDev** [comment]
Sorry for the long wait.

To fix this issue just remove the background styles from tailwind that get added in your Post.vue Line 74 and 77. This should fix your styling problem.

Page Query will not be highlighted in the near future, will have to check if shiki or this plugin can incoperate the custom syntax generation from vetur.
