### ISSUE TITLE
Cannot work with gridsome-plugin-remark-twitter

### ISSUE THREAD

**Issue by mallim** [EldoranDev/gridsome-plugin-remark-shiki#8]
Referring to danvega/gridsome-plugin-remark-twitter#3

The twitter http link will not get rendered given the following configuration:

      plugins: [
        [
          "gridsome-plugin-remark-shiki",
          {
            theme: "min-dark",
            skipInline: true
          },
          "gridsome-plugin-remark-twitter"
        ]
      ]

**Comment by EldoranDev** [comment]
Your config might be faulty,

try

plugins: [
        [
          "gridsome-plugin-remark-shiki",
          {
            theme: "min-dark",
            skipInline: true
          },
        ],
          "gridsome-plugin-remark-twitter"
      ]
The plugins should not be in the same array.

If that does not fix things, could you provide me a sample repository ?

**Comment by mallim** [comment]
Thanks for your help. Finally able to use gridsome-plugin-remark-twitter
